### PR TITLE
methods for position and bearing

### PR DESCRIPTION
**Pull request by choldgraf**
two helper methods to set the position / bearing of the turtle.

I also tried (and failed) to implement a pensize method, but none of the attributes I changed in the JS changed the size of the actual pen :-/

WDYT?

### CODE REVIEW

**Comment by takluyver** [comment]
LGTM. How close do we want to stick to the Python turtle API? I notice that the [setposition() method](https://docs.python.org/3/library/turtle.html#turtle.setposition) in vanilla turtle doesn't take a bearing. I'm not particularly concerned about being API compatible myself.

It looks like [this line](https://github.com/takluyver/mobilechelonian/blob/21f3c2c50902baccc8004235dc42da8646bc1739/mobilechelonian/mobilechelonianjs/turtlewidget.js#L106) is where the pen size will need to be connected to. You probably also need to change the if condition there to see changes in pen size as well.

**Comment by choldgraf** [comment]
yeah I figured that it'd be OK to break from that API since it's a kwarg and we wouldn't need to show its use if we didn't want to. I mostly just put it there so that we could do both movement + rotation without adding two different points, though I could go either way on that

re: strokewidth, I thought I tried changing that but to no avail...I can give it another shot in a bit.

also, what do you think about adding an attribute that just returns a list of `x, y` pairs corresponding to each point in the turtle's path?

**Comment by takluyver** [comment]
> re: strokewidth, I thought I tried changing that but to no avail...I can give it another shot in a bit.

I just noticed that there are two places in that file where strokeWidth is set - did you get both of them?

> also, what do you think about adding an attribute that just returns a list of x, y pairs corresponding to each point in the turtle's path?

I don't see any reason not to. :-)

**Comment by choldgraf** [comment]
I believe there is also a `lineSize` parameter too...not sure how that's different from `strokeWidth`. When I give it a shot I'll make a PR and we can iterate from there :-)

**Comment by takluyver** [comment]
OK, let's drop the pensize() method from this PR as it doesn't currently do anything, then.

**Comment by choldgraf** [comment]
ah shit - forgot that I'd already written that into the python code. I had edited the JS a bunch but reverted it before pushing since it didn't work...I forgot to do the same w/ the python :-)

**Comment by choldgraf** [comment]
ok I think that did it, LMK!

**Comment by takluyver** [comment]
Thanks!

**Comment by takluyver** [comment]
I've invited you as a collaborator on the repo. I'd still like to look over your changes before we merge them, but I want to acknowledge that you're doing most of the work on it at the moment. It also reduces the bus factor for the project. :-)

**Comment by choldgraf** [comment]
sounds great! I'm good w/ that :-)

out of curiosity where does the name come from?

**Comment by takluyver** [comment]
'De chelonian mobile' is the title of a fictional book in Small Gods, the
book quoted in the readme. It means 'the turtle moves'. Small Gods is set
on the discworld, a flat world carried through space by a giant turtle. In
a parody of the Galileo affair, a religious group on the discworld believes
that their world is a sphere, so the book describing the existence of the
turtle becomes a heretical tract. The quote in the readme is an echo of
Galileo's apocryphal "and yet it moves" after renouncing his view that the
earth moves round the sun.

It's a long and unwieldy name, but it was just too good to miss. If you
haven't read the discworld books, allow me to recommend them.

**Comment by choldgraf** [comment]
haha that is an awesomely thorough answer! and here I was thinking it could be called `jupyturtle` :-P

I still haven't gotten to discworld...it's been on my list for a while but one of those things it seems like will take a lotta commitment to really get into. On the topic of awesome philosophical scifi style books, check out The Three Body Problem series...just finished book 1 and it is cool!

**Comment by takluyver** [comment]
Thanks for the tip! I'll look out for it. I'm sure I coincidentally heard of that series the other day, and now I can't think where.

**Pull request merged**
