### PR TITLE
Make the repo binder-compliant

### PR DESCRIPTION
**Pull request by choldgraf**
I was speaking with a high-school teacher who wanted to use Binder to teach turtle for his students. To that extent I thought it might be nice to create a Binder link for this repo so that people can quickly play around with it!

This PR adds three main things:

1. A `try.ipynb` notebook that shows some of the functionality of the package and encourages users to experiment.
2. `environment.yml` (I'm using conda because it's simpler to get ipywidgets installed)
3. A Binder badge to `README.rst` so users can click.

If it gets merged, we should switch the org name in the Binder link to `takluyver`

Here's the Binder link itself (for my repo):

https://beta.mybinder.org/v2/gh/choldgraf/mobilechelonian/master?filepath=try.ipynb

### CODE REVIEW

**Comment by takluyver** [comment]
Cool! I'm happy to merge this - do you want to change the link pre-emptively or after merging?

**Comment by choldgraf** [comment]
here's the new link: https://beta.mybinder.org/v2/gh/takluyver/mobilechelonian/master?filepath=try.ipynb

looks good?

**Comment by takluyver** [comment]
Looks good, thanks :-)

**Comment by choldgraf** [comment]
woo!

**Pull request merged**
